message:
  info_discord: "§7[§9!§7] §9Voici notre discord : §7https://discordapp.com/invite/5prNyYx"
  info_site: "§7[§c!§7] §cSite actuellement indisponible"
help:
  1: "    §aAide §8- §6Hutopya "
  2: "§c/island §8- §aAide pour les îles"