elytreparcours:
  1:
    x:
    y:
    z:
    w:
  2:
    x:
    y:
    z:
    w:
  3:
    x:
    y:
    z:
    w:
  4:
    x:
    y:
    z:
    w:
  5:
    x:
    y:
    z:
    w:
  6:
    x:
    y:
    z:
    w:
  7:
    x:
    y:
    z:
    w:
  8:
    x:
    y:
    z:
    w:
  9:
    x:
    y:
    z:
    w: